name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore Notex.sln
      
    - name: Build
      run: dotnet build Notex.sln --configuration Release --no-restore
      
    - name: Run Unit Tests
      run: dotnet test --configuration Release --no-build --verbosity minimal ./tests/Notex.UnitTests/Notex.UnitTests.csproj

  integration:
    name: Build and run integration tests
    needs: [build]
    runs-on: ubuntu-latest
    env:
      ConnectionStrings__Default: "Server=localhost;Port=3306;Database=notex_integration_tests;Uid=root;Pwd=rootpassword;pooling=true;CharSet=utf8;"
      DB_DATABASE: notex_integration_tests
      DB_USER: root
      DB_PASSWORD: rootpassword
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore Notex.sln

      - name: Build
        run: dotnet build Notex.sln --configuration Release --no-restore

      - name: Run Integration Tests
        run: dotnet test --configuration Release --no-build --verbosity minimal ./tests/Notex.IntegrationTests/Notex.IntegrationTests.csproj